django/apps/questions/urls.py
from django.urls import path
from .views import *
from apps.questions.views import *

app_name = 'questions'
urlpatterns = [
	path('', QuestionList.as_view(), name='question'),
	path('create/', QuestionCreate.as_view(), name='create'),
	path('<int:pk>', QuestionDetail.as_view(), name='detail'),
	path('edit/<int:pk>', QuestionView.as_view(), name='edit'),
	path('delete/<int:pk>', QuestionDelete.as_view(), name='delete'),
]

django/diufirstprocjet/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordChangeView, PasswordResetCompleteView
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', TemplateView.as_view(template_name='home.html') , name='home'),
    path('realtime/', include('apps.realtime.urls', namespace='realtime')),
    path('arduino/', include('apps.arduino.urls', namespace='arduino')),
    path('users/', include('apps.users.urls', namespace='users')),
    path('roles/', include('apps.roles.urls', namespace='roles')),
    path('questions/', include('apps.questions.urls', namespace='questions')),
    path('', LoginView.as_view(template_name='login.html'), name="login"),
    path('logout/', LogoutView.as_view(template_name='login.html'), name="logout"),
    path('topics/', include('apps.topics.urls', namespace='topics')),
    path('courses/', include('apps.courses.urls', namespace='courses')),
    path('games/', include('apps.games.urls', namespace='games')),
    path('califications/', include('apps.califications.urls', namespace='califications')),
]

django/apps/questions/models.py
from django.db import models

class Question(models.Model):
	name = models.CharField(max_length=512, null=False, blank=False)
	statement = models.TextField(null=False, blank=False)
	answer_1 = models.CharField(max_length=512, null=True, blank=True)
	answer_2 = models.CharField(max_length=512, null=True, blank=True)
	answer_3 = models.CharField(max_length=512, null=True, blank=True)
	answer_4 = models.CharField(max_length=512, null=True, blank=True)
	answer_5 = models.CharField(max_length=512, null=True, blank=True)
	correct_answer = models.CharField(max_length=32, null=False, blank=False)
	video = models.CharField(blank=False, max_length=500)
	completed = models.BooleanField(default=False)
	current = models.BooleanField(default=False)
	def __str__(self):
		return self.name

django/apps/questions/forms.py
from apps.questions.models import *
from django import forms
        
class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = (
            'id',
            'name',
        	'statement',
            'video',
            'answer_1',
            'answer_2',
            'answer_3',
            'answer_4',
            'answer_5',
            'correct_answer')
        labels = {
            'name':'Nombre',
            'statement':'Enunciado',
            'video':'Multimedia',
        }

django/apps/questions/views.py
from django.shortcuts import render
from django.views.generic import ListView,CreateView,UpdateView,DeleteView,DetailView
from apps.questions.models import Question
from apps.questions.forms import QuestionForm
from django.urls import reverse_lazy

class QuestionList(ListView):
    model = Question
    template_name = 'question.html'

class QuestionDetail(DetailView):
    model = Question
    template_name = 'question_detail.html'

class QuestionCreate(CreateView):
    model = Question
    form_class = QuestionForm
    template_name = 'question_form.html'
    success_url = reverse_lazy('questions:question')

class QuestionView(UpdateView):
    model = Question
    form_class = QuestionForm
    template_name = 'question_form.html'
    success_url = reverse_lazy('questions:question')

class QuestionDelete(DeleteView):
    model = Question
    success_url = reverse_lazy('questions:question')

django/apps/questions/templates/question.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block page_title %}
    Listado de preguntas
{% endblock %}

{% block content %}
    <a class="btn btn-info float-right" href="{% url 'questions:create' %}">Nuevo pregunta</a>
    <br>
    <hr>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Enunciado</th>
                <th>Video</th>
                <th class="text-center">Opciones</th>
            </tr>
        </thead>
        <tbody>
            {% for question in object_list %}
            <tr>
                <td>{{ question.name }}</td>
                <td>{{ question.statement }}</td>
                <td>{{ question.video }}</td>
                <td class="text-center">
                    <a class="btn text-danger" href="{% url 'questions:edit' pk=question.id %}"><i class="fas fa-edit"></i></a>
                    <a class="btn text-info" href="{% url 'questions:detail' pk=question.id %}"><i class="far fa-eye"></i></a>
                    <button class="btn text-danger" data-toggle="modal" data-target="#delete_modal_{{ question.id }}">
                        <i class="far fa-trash-alt"></i>
                    </button>
                    <div class="modal fade" id="delete_modal_{{ question.id }}" tabindex="-1">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">Eliminar</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    Esta seguro de elimiar la pregunta "{{ question.question }}"
                                </div>
                                <div class="modal-footer">
                                    <form action="{% url 'users:delete' question.id %}" method="POST">
                                        {% csrf_token %}
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                                        <button type="submit" class="btn btn-danger">Aceptar</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    {% if questions.has_other_pages %}
    <ul class="pagination">
        {% if questions.has_previous %}
        <li><a href="?page={{ users.previous_page_number }}">&laquo;</a></li>
        {% else %}
        <li class="disabled"><span>&laquo;</span></li>
        {% endif %}
        {% for i in questions.paginator.page_range %}
        {% if questions.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
        {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
        {% endif %}
        {% endfor %}
        {% if questions.has_next %}
        <li><a href="?page={{ users.next_page_number }}">&raquo;</a></li>
        {% else %}
        <li class="disabled"><span>&raquo;</span></li>
        {% endif %}
    </ul>
    {% endif %}
{% endblock %}

django/apps/questions/templates/question_detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block page_title %}
    Crear pregunta
{% endblock %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-lg-6 col-md-6 col-sm-12">
			

			
		</div>
	</div>
</div>
<div class="container h-100">
    <div class="row align-items-center h-100">
        <div class="col-8 mx-auto">
            <div class="jumbotron" style="padding-top: 0.5rem;">
            	<h4 class="text-center">Detalle de la pregunta</h4>
            	<div class="form-group">
            		<label>Nombre</label>
            		<input type="text" value="{{question.name}}" class="form-control">
            	</div>
            	<div class="form-group">
            		<label>Enunciado</label>
            		<input type="text" value="{{question.statement}}" class="form-control">
            	</div>
            	<div class="form-group">
            		<label>Video</label>
            		<input type="text" value="{{question.video}}" class="form-control">
            	</div>
            	<h5>Respuestas</h5>
            	<ol>
	            	{% if question.answer_1 %}
	            	<li> {{question.answer_1}} </li>
	            	{% endif %}

	            	{% if question.answer_2 %}
	            	<li> {{question.answer_2}} </li>
	            	{% endif %}

	            	{% if question.answer_3 %}
	            	<li> {{question.answer_3}} </li>
	            	{% endif %}

	            	{% if question.answer_4 %}
	            	<li> {{question.answer_4}} </li>
	            	{% endif %}

	            	{% if question.answer_5 %}
	            	<li> {{question.answer_5}} </li>
	            	{% endif %}
	            </ol>
	            <h5>Respuesta Correcta</h5>
	            <ul>
		           	{% if question.correct_answer == 'answer_1' %} 
		           		<li>Numeral 1</li>
		           	{% elif question.correct_answer == 'answer_2' %}
		           		<li>Numeral 2</li>
		           	{% elif question.correct_answer == 'answer_3' %}
		           		<li>Numeral 3</li>
		           	{% elif question.correct_answer == 'answer_4' %}
		           		<li>Numeral 4</li>
		           	{% elif question.correct_answer == 'answer_5' %}
		           		<li>Numeral 4</li>
		           	{% endif %}
	            </ul>
            </div>
        </div>
    </div>
</div>
{% endblock %}

django/apps/questions/templates/question_form.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block page_title %}
    Crear pregunta
{% endblock %}

{% block content %}
	<div class="container h-100">
	    <div class="row align-items-center h-100">
	        <div class="col-8 mx-auto">
	            <div class="jumbotron" style="padding-top: 0.5rem;">
	            	<h4 class="text-center">Nueva Pregunta</h4>
	            	<form method="POST" id="create-question-form">
	            		{% csrf_token %}
	            		{% bootstrap_field form.name %}
	            		{% bootstrap_field form.statement %}
	            		{% bootstrap_field form.video %}
		            	<hr>

		            	{% if form.instance.name %}
		            		<h3>Respuestas</h3>
		            	{% else %}
		            		<h3>Agregar Respuestas</h3>
		            	{% endif %}

		            	<div class="form-group">
			            	<button type="button" id="add-answer" class="btn btn-link">
			            		Agregar respuesta  <i class="fas fa-plus"></i>
			            	</button>
			            	<div id="answer-1" style="display:{% if form.instance.answer_1 %}inline{% else %}none{% endif %};">
			            		<div class="input-group mb-3">
			            			<div class="input-group-prepend">
			            				<div class="input-group-text">
			            					<input 
			            					type="radio" 
			            				 	name="correct_answer" 
			            				 	value="answer_1"
			            				 	{% if form.instance.correct_answer == 'answer_1' %} checked {% endif %}>
			            				</div>
			            			</div>
			            			<input 
			            			type="text" 
			            			class="form-control" 
			            			name="answer_1"
			            			value="{% if form.instance.answer_1 %}{{form.instance.answer_1}}{% endif %}">
			            		</div>
			            	</div>
			            	<div id="answer-2" style="display:{% if form.instance.answer_2 %}inline{% else %}none{% endif %};">
				            	<div class="input-group mb-3">
				            		<div class="input-group-prepend">
				            			<div class="input-group-text">
				            				<input type="radio" 
				            				name="correct_answer" 
				            				value="answer_2"
				            				{% if form.instance.correct_answer == 'answer_2' %} checked {% endif %}>
				            			</div>
				            		</div>
				            		<input 
				            		type="text" 
				            		class="form-control" 
				            		name="answer_2" 
				            		value="{% if form.instance.answer_2 %}{{form.instance.answer_2}}{% endif %}">
				            	</div>
				            </div>
				            <div id="answer-3" style="display:{% if form.instance.answer_3 %}inline{% else %}none{% endif %};">
				            	<div class="input-group mb-3" >
				            		<div class="input-group-prepend">
				            			<div class="input-group-text">
				            				<input 
				            				type="radio" 
				            				name="correct_answer" 
				            				value="answer_3"
				            				{% if form.instance.correct_answer == 'answer_3' %} checked {% endif %}>
				            			</div>
				            		</div>
				            		<input 
				            		type="text" 
				            		class="form-control" 
				            		name="answer_3"
				            		value="{% if form.instance.answer_3 %}{{form.instance.answer_3}}{% endif %}">
				            	</div>
				            </div>
				            <div id="answer-4" style="display:{% if form.instance.answer_4 %}inline{% else %}none{% endif %};">
				            	<div class="input-group mb-3">
				            		<div class="input-group-prepend">
				            			<div class="input-group-text">
				            				<input 
				            				type="radio" 
				            				name="correct_answer" 
				            				value="answer_4"
				            				{% if form.instance.correct_answer == 'answer_4' %} checked {% endif %}>
				            			</div>
				            		</div>
				            		<input 
				            		type="text" 
				            		class="form-control" 
				            		name="answer_4"
				            		value="{% if form.instance.answer_4 %}{{form.instance.answer_4}}{% endif %}">
				            	</div>
				            </div>
				            <div id="answer-5" style="display:{% if form.instance.answer_5 %}inline{% else %}none{% endif %};">
				            	<div class="input-group mb-3">
				            		<div class="input-group-prepend">
				            			<div class="input-group-text">
				            				<input 
				            				type="radio" 
				            				name="correct_answer" 
				            				value="answer_5"
				            				{% if form.instance.correct_answer == 'answer_5' %} checked {% endif %}>
				            			</div>
				            		</div>
				            		<input 
				            		type="text" 
				            		class="form-control" 
				            		name="answer_5" 
				            		value="{% if form.instance.answer_5 %}{{form.instance.answer_5}}{% endif %}">
				            	</div>
				            </div>
			            </div>
		        	</form>

	            	<div class="form-group">
	            		<button type="submit" class="btn btn-warning" form="create-question-form">
	            			Guardar
	            		</button> 
	            	</div>
	            </div>
	        </div>
	    </div>
	</div>
{% endblock %}

{% block js %}
<script type="text/javascript">
	var show_answer = 0;
	{% if form.instance.answer_1 %} show_answer++; {% endif %}
	{% if form.instance.answer_2 %} show_answer++; {% endif %}
	{% if form.instance.answer_3 %} show_answer++; {% endif %}
	{% if form.instance.answer_4 %} show_answer++; {% endif %}
	{% if form.instance.answer_5 %} show_answer++; {% endif %}


	$("#add-answer").click(function() {
		show_answer ++;
		$("#answer-"+show_answer).attr("style", "display:block; width:100%;");
	});
	$("#create-question-form").submit(function(event){
		if(show_answer < 3){
			event.preventDefault();
			toastr.error("Debe completar al menos 3 respuestas", "Error en Respuestas!");
		}
		for(var i=1; i<=show_answer; i++){
			if($("#answer-"+i+" input").eq(1).val()==""){
				event.preventDefault();
				toastr.error("Debes completar las respuestas seleccionadas", "Error en Respuestas!");
				return false;
			}
		}
		var count = 0;
		for(var i=1; i<=show_answer; i++){ 
			if($("#answer-"+i+" input").eq(0).is(":checked")){
				count ++;
			}
		}
		if(count == 0){
			event.preventDefault();
			toastr.error("Debes seleccionar una respuesta correcta", "Error en Respuestas!");
			return false;
		}
	});
</script>
{% endblock %}