django/apps/users/urls.py
from django.urls import path
from .views import *
from apps.users.views import UserListView, UserDeleteView, UserDetailView
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordChangeView, PasswordResetCompleteView

app_name = 'users'
urlpatterns = [
	path('', UserListView.as_view(), name='users'),
	path('create/', create, name='create'),
	path('<int:pk>', UserDetailView.as_view(), name='detail'),
	path('edit/<int:pk>', edit, name='edit'),
	path('delete/<int:pk>', UserDeleteView.as_view(), name='delete'),
	path('home/', home, name='home')
	# path('login/', LoginView.as_view(template_name='login.html'), name="login"),
]

django/diufirstprocjet/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordChangeView, PasswordResetCompleteView
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', TemplateView.as_view(template_name='home.html') , name='home'),
    path('realtime/', include('apps.realtime.urls', namespace='realtime')),
    path('arduino/', include('apps.arduino.urls', namespace='arduino')),
    path('users/', include('apps.users.urls', namespace='users')),
    path('roles/', include('apps.roles.urls', namespace='roles')),
    path('questions/', include('apps.questions.urls', namespace='questions')),
    path('', LoginView.as_view(template_name='login.html'), name="login"),
    path('logout/', LogoutView.as_view(template_name='login.html'), name="logout"),
    path('topics/', include('apps.topics.urls', namespace='topics')),
    path('courses/', include('apps.courses.urls', namespace='courses')),
    path('games/', include('apps.games.urls', namespace='games')),
    path('califications/', include('apps.califications.urls', namespace='califications')),
]

django/apps/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import MinLengthValidator

class User(AbstractUser):
    id_card = models.CharField(max_length=10, unique=True, validators=[MinLengthValidator(8, 'Mínimo 8 dígitos')])
    address = models.CharField(max_length=50)
    birthday = models.DateField(null=True)
    phone = models.CharField(max_length=11)

    def __str__(self):
    	return self.get_full_name()

django/apps/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import Group
from apps.users.models import *


class UserForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user',None)
        super(UserForm, self).__init__(*args, **kwargs)
        instance = getattr(self, 'instance', None)
        # Se está actualizando el usuario, por lo tanto no es necesario el campo password de confirmación.
        # También se puede cambiar el campo password1 a texto normal, para ver qué pass se va poner
        if instance and instance.pk:
            self.fields['password1'] = forms.CharField(label='Password', required=False, widget=forms.PasswordInput)
            del self.fields['password2']
            self.fields['username'].widget.attrs['readonly'] = True

        if self.user.groups.filter(name='docente').exists():
            self.fields['groups'].queryset = Group.objects.filter(name='estudiante')

    class Meta:
        model = User
        fields = (
            'id',
        	'first_name', 
        	'last_name', 
        	'id_card', 
        	'username', 
            'groups', 
            'birthday', 
            'phone', 
            'email', 
            'address', 
            'is_active',
            'password1', 
            'password2',)

django/apps/users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView,UpdateView,DeleteView,DetailView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from apps.users.models import User
from django.contrib.auth.models import Group
from apps.users.forms import UserForm
from django.urls import reverse_lazy
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.decorators import permission_required

@method_decorator(login_required, name='dispatch')
class UserListView(PermissionRequiredMixin, ListView):
    model = User
    permission_required = 'users.view_user'
    template_name = 'users.html'

@login_required
@permission_required('users.add_user')
def create(request):
    form = UserForm(request.POST or None, user=request.user)
    if request.method == 'POST':
        if form.is_valid():
            user = form.save()
            for g in request.POST.getlist('groups'):
                group = Group.objects.get(pk=g)
                user.groups.add(group)
            return redirect('users:users')
    return render(request, 'user_form.html', {'form':form})

@login_required
@permission_required('users.change_user')
def edit(request, pk):
    instance = get_object_or_404(User, pk=pk)
    form = UserForm(request.POST or None, instance=instance, user=request.user)
    if request.method == 'POST':
        if form.is_valid():
            user = form.save(commit=False)
            password = request.POST.get('password1', '')

            if password == '':
                user.password = instance.password
            else: 
                user.set_password(password)
                print(user.username)

            user = form.save()
            user.groups.clear()
            for g in request.POST.getlist('groups'):
                group = Group.objects.get(pk=g)
                user.groups.add(group)
            return redirect('users:users')
    return render(request, 'user_form.html', {'form':form})

@method_decorator(login_required, name='dispatch')
class UserDetailView(PermissionRequiredMixin, DetailView):
    model = User
    permission_required = 'users.view_role'
    template_name = 'user_detail.html'

@method_decorator(login_required, name='dispatch')
class UserDeleteView(PermissionRequiredMixin, DeleteView):
    model = User
    permission_required = 'users.delete_user'
    success_url = reverse_lazy('users:users')

def home(request):
    if request.user.groups.filter(name = 'estudiante').exists():
        return redirect('games:play_game')
    else : 
        return redirect('home')

django/apps/users/templates/user_detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block page_title %}
    Crear Usuario
{% endblock %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-lg-6 col-md-6 col-sm-12">
			<div class="form-group">
				<label>Nombre</label>
				<input type="text" value="{{user.first_name}}" class="form-control">
			</div>
			<div class="form-group">
				<label>Apellido</label>
				<input type="text" value="{{user.last_name}}" class="form-control">
			</div>
			<div class="form-group">
				<label>email</label>
				<input type="text" value="{{user.email}}" class="form-control">
			</div>
			<div class="form-group">
				<label>Teléfono</label>
				<input type="text" value="{{user.phone}}" class="form-control">
			</div>
			<div class="form-group">
				<label>Grupos</label>
				<ul>
					{% for group in user.groups.all %}
						<li>{{group.name}}</li>
					{% endfor %}
				</ul>
			</div>
		</div>
	</div>
</div>
{% endblock %}

django/apps/users/templates/user_form.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block page_title %}
    Crear Usuario
{% endblock %}

{% block content %}
	{{uss}}
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-warning">
    </form>
{% endblock %}

django/apps/users/templates/users.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block page_title %}
    Listado de usuario
{% endblock %}

{% block content %}
    <a class="btn btn-info float-right" href="{% url 'users:create' %}">Nuevo Usuario</a>
    <br>
    <hr>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Usuario</th>
                <th>Email</th>
                <th>Primer Nombre</th>
                <th>Primer Apellido</th>
                <th class="text-center">Opciones</th>
            </tr>
        </thead>
        <tbody>
            {% for user in object_list %}
            <tr>
                <td>{{ user.username }}</td>
                <td>{{ user.email }}</td>
                <td>{{ user.first_name }}</td>
                <td>{{ user.last_name }}</td>
                <td class="text-center">
                    <a class="btn text-danger" href="{% url 'users:edit' pk=user.id %}"><i class="fas fa-edit"></i></a>
                    <a class="btn text-info" href="{% url 'users:detail' pk=user.id %}"><i class="far fa-eye"></i></a>
                    <button class="btn text-danger" data-toggle="modal" data-target="#delete_modal_{{ user.id }}">
                        <i class="far fa-trash-alt"></i>
                    </button>
                    <div class="modal fade" id="delete_modal_{{ user.id }}" tabindex="-1">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">Eliminar</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    Esta seguro de elimiar el usuario "{{ user.first_name_1 }}"
                                </div>
                                <div class="modal-footer">
                                    <form action="{% url 'users:delete' user.id %}" method="POST">
                                        {% csrf_token %}
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                                        <button type="submit" class="btn btn-danger">Aceptar</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    {% if users.has_other_pages %}
    <ul class="pagination">
        {% if users.has_previous %}
        <li><a href="?page={{ users.previous_page_number }}">&laquo;</a></li>
        {% else %}
        <li class="disabled"><span>&laquo;</span></li>
        {% endif %}
        {% for i in users.paginator.page_range %}
        {% if users.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
        {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
        {% endif %}
        {% endfor %}
        {% if users.has_next %}
        <li><a href="?page={{ users.next_page_number }}">&raquo;</a></li>
        {% else %}
        <li class="disabled"><span>&raquo;</span></li>
        {% endif %}
    </ul>
    {% endif %}
{% endblock %}