django/apps/games/urls.py
from django.urls import path
from .views import *

app_name = 'games'

urlpatterns = [
	path('', GameListView.as_view(), name='games'),
	path('create/', GameCreateView.as_view(), name='create'),
	path('<int:pk>', GameDetailView.as_view(), name='detail'),
	path('edit/<int:pk>', GameUpdateView.as_view(), name='edit'),
	path('delete/<int:pk>', GameDeleteView.as_view(), name='delete'),
	path('play_game/', PlayGameView.as_view(), name='play_game'),
	path('read_text/', read_text, name='read_text'),
	path('test/<int:pk>', NewGameView.as_view(), name='test'),
	path('start/', start, name='start'),
	path('stop/', stop, name='stop'),
]

django/diufirstprocjet/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordChangeView, PasswordResetCompleteView
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', TemplateView.as_view(template_name='home.html') , name='home'),
    path('realtime/', include('apps.realtime.urls', namespace='realtime')),
    path('arduino/', include('apps.arduino.urls', namespace='arduino')),
    path('users/', include('apps.users.urls', namespace='users')),
    path('roles/', include('apps.roles.urls', namespace='roles')),
    path('questions/', include('apps.questions.urls', namespace='questions')),
    path('', LoginView.as_view(template_name='login.html'), name="login"),
    path('logout/', LogoutView.as_view(template_name='login.html'), name="logout"),
    path('topics/', include('apps.topics.urls', namespace='topics')),
    path('courses/', include('apps.courses.urls', namespace='courses')),
    path('games/', include('apps.games.urls', namespace='games')),
    path('califications/', include('apps.califications.urls', namespace='califications')),
]

django/apps/games/models.py
from django.db import models
from apps.courses.models import Course
from apps.topics.models import Topic

class Game(models.Model):
	name = models.CharField(max_length=128, null=False, blank=False)
	description = models.CharField(max_length=512, null=True, blank=True)
	course = models.ForeignKey(Course, on_delete=models.CASCADE, null=True, blank=True)
	topics = models.ManyToManyField(Topic)
	completed = models.BooleanField(default=False)
	current = models.BooleanField(default=False)
	arduino_task_id = models.CharField(max_length=256, null=True)
	waiting_topic = models.BooleanField(default=False)
	waiting_answer = models.BooleanField(default=False)
	reading_topic = models.BooleanField(default=False)
	reading_question = models.BooleanField(default=False)
	channel = models.CharField(max_length=64, null=True, blank=True)
	user_id = models.CharField(max_length=10, null=True, blank=True)

	def __str__(self):
		return self.name

django/apps/games/forms.py
from django import forms
from apps.games.models import Game
from apps.questions.models import Question
from apps.courses.models import Course


class GameForm(forms.ModelForm):

	def __init__(self, *args, **kwargs):
		super(GameForm, self).__init__(*args, **kwargs)
		self.fields['course'].queryset = Course.objects.all()
		
	class Meta:
		model = Game
		fields = (
			'id',
			'name',
			'description',
			'course',
			'topics'
		)

django/apps/games/views.py
from django.shortcuts import render, get_object_or_404
from django.template.response import TemplateResponse
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import ListView,CreateView,UpdateView,DeleteView,DetailView,TemplateView
from apps.games.models import Game
from apps.topics.models import Topic
from apps.questions.models import Question
from apps.games.forms import GameForm
from django.urls import reverse_lazy
from django.contrib.auth.mixins import PermissionRequiredMixin
from diufirstprocjet.celery import app
from celery.task.control import revoke, inspect
import pyttsx3 as tts
from apps.realtime.tasks import listenArduino, listenBluetooth, readText, initGame, stopGame, readTopic
from apps.califications.views import sendNote
from celery.app.task import Task
import json

from .control import test

@method_decorator(login_required, name='dispatch')
class GameListView(PermissionRequiredMixin, ListView):
    model = Game
    permission_required = 'games.view_game'
    template_name = 'games.html'

@method_decorator(login_required, name='dispatch')
class GameDetailView(PermissionRequiredMixin, DetailView):
    model = Game
    permission_required = 'games.view_game'
    template_name = 'game_detail.html'

@method_decorator(login_required, name='dispatch')
class GameCreateView(PermissionRequiredMixin, CreateView):
    model = Game
    permission_required = 'games.add_game'
    form_class = GameForm
    template_name = 'game_form.html'
    success_url = reverse_lazy('games:games')

@method_decorator(login_required, name='dispatch')
class GameUpdateView(PermissionRequiredMixin, UpdateView):
    model = Game
    permission_required = 'games.change_game'
    form_class = GameForm
    template_name = 'game_form.html'
    success_url = reverse_lazy('games:games')

@method_decorator(login_required, name='dispatch')
class GameDeleteView(PermissionRequiredMixin, DeleteView):
    model = Game
    permission_required = 'games.delete_game'
    success_url = reverse_lazy('games:games')    

class PlayGameView(TemplateView):
    # template_name = 'play_game.html'
    template_name = 'play_game2.html'
    def get_context_data(self, **kwargs):
        # test()
        context = super(PlayGameView, self).get_context_data(**kwargs)
        user= self.request.user 
        course = user.course_set.all()[0]
        game = course.game_set.all()[0]
        print(user.groups.all())
        print(course)
        print(game)
        context['game'] = game
        app.control.purge()
        return context

    def post(self, request, *args, **kwargs):
        if self.request.POST.get('option') == '1':
            app.control.purge()
            task_id = listenArduino.delay()
            return HttpResponse(task_id)
        elif self.request.POST.get('option') == '2':
            revoke(self.request.POST.get('task_id'), terminate=True)
            return HttpResponse('off')
        return HttpResponse('ok')


class NewGameView(TemplateView):
    template_name = 'new_game.html'
    def get_context_data(self, **kwargs):
        context = super(NewGameView, self).get_context_data(**kwargs)
        context['game'] = get_object_or_404(Game, pk='1')
        app.control.purge()
        return context

    def post(self, request, *args, **kwargs):
        task_id = listenBluetooth.delay()
        return HttpResponse(task_id)
"""
def control(request):
    action = request.GET.get("action", "")
    task_id = request.GET.get("task_id", "")
    response_data = {}
    if action == "start":
        if task_id == "":
            task_id = test_button.delay()
            response_data['task'] = "running"
            response_data['task_id'] = str(task_id)
        else:
            Task.update_state(self=app, task_id=task_id, state='RUNNING')
            response_data['task'] = "re-running"
            response_data['task_id'] = str(task_id)
    elif action == "pause":
        response_data['task'] = "paused"
        response_data['task_id'] = str(task_id)
        Task.update_state(self=app, task_id=task_id, state='PAUSE')
    else:
        revoke(task_id, terminate=True)
        response_data['task'] = "terminated"
        response_data['task_id'] = ""
    return HttpResponse(json.dumps(response_data))
"""

def read_text(request):
    text = request.POST.get("text")
    key_topic = request.POST.get("key_topic")
    key_question = request.POST.get("key_question")
    to_read = request.POST.get("to_read")
    task_id = readText.delay(text=text, key_topic=key_topic, key_question=key_question, to_read=to_read)
    return HttpResponse(task_id)

"""
######################### Para el proyecto 2 #########################################
"""
def start(request):
    game_id = request.GET.get("game_id")
    # Se instancia el juego o partida
    game = get_object_or_404(Game, pk=game_id)
    if game:
        channel_game = "channelgame"+str(game.id)
        game.channel = channel_game
        game.user_id = request.user.id
        game.save()
        initGame.delay(game_id=game_id)
        response_data = {}
        response_data['task'] = "running"
        response_data['channel'] = channel_game
        return HttpResponse(json.dumps(response_data))
    return HttpResponse(json.dumps({}))

def stop(request):
    game_id = request.GET.get("game_id")
    task_id = stopGame.delay(game_id=game_id)
    response_data = {}
    response_data['task'] = "running"
    response_data['task_id'] = str(task_id)
    return HttpResponse(json.dumps(response_data))





        

django/apps/games/templates/game_detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block page_title %}
    Detalle de la partida
{% endblock %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-lg-6 col-md-6 col-sm-12">
			<div class="form-group">
				<label>Nombre</label>
				<input type="text" value="{{game.name}}" class="form-control">
			</div>
			<div class="form-group">
				<label>Descripción</label>
				<input type="text" value="{{game.description}}" class="form-control">
			</div>
			<div class="form-group">
				<label>Curso</label>
				<input type="text" value="{{game.course}}" class="form-control">
			</div>
			<hr>
			<div class="form-group">
				<label>Preguntas</label>
				<ul>
					{% for question in game.questions.all %}
						<li>{{question.name}}</li>
					{% endfor %}
				</ul>
			</div>
		</div>
	</div>
</div>
{% endblock %}

django/apps/games/templates/game_form.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block page_title %}
    Crear Partida
{% endblock %}

{% block content %}
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-warning">
    </form>
{% endblock %}

django/apps/games/templates/games.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block page_title %}
    Listado de partidas
{% endblock %}

{% block content %}
    <a class="btn btn-info float-right" href="{% url 'games:create' %}">Nueva Partida</a>
    <br>
    <hr>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Descripción</th>
                <th class="text-center">Opciones</th>
            </tr>
        </thead>
        <tbody>
            {% for game in object_list %}
            <tr>
                <td>{{ game.name }}</td>
                <td>{{ game.description }}</td>
                <td class="text-center">
                    <a class="btn text-danger" href="{% url 'games:edit' pk=game.id %}"><i class="fas fa-edit"></i></a>
                    <a class="btn text-info" href="{% url 'games:detail' pk=game.id %}"><i class="far fa-eye"></i></a>
                    <button class="btn text-danger" data-toggle="modal" data-target="#delete_modal_{{ game.id }}">
                        <i class="far fa-trash-alt"></i>
                    </button>
                    <div class="modal fade" id="delete_modal_{{ game.id }}" tabindex="-1">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">Eliminar</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    Esta seguro de elimiar la partida "{{ game.name }}"?
                                </div>
                                <div class="modal-footer">
                                    <form action="{% url 'games:delete' game.id %}" method="POST">
                                        {% csrf_token %}
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                                        <button type="submit" class="btn btn-danger">Aceptar</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    {% if games.has_other_pages %}
    <ul class="pagination">
        {% if games.has_previous %}
        <li><a href="?page={{ games.previous_page_number }}">&laquo;</a></li>
        {% else %}
        <li class="disabled"><span>&laquo;</span></li>
        {% endif %}
        {% for i in games.paginator.page_range %}
        {% if games.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
        {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
        {% endif %}
        {% endfor %}
        {% if games.has_next %}
        <li><a href="?page={{ games.next_page_number }}">&raquo;</a></li>
        {% else %}
        <li class="disabled"><span>&raquo;</span></li>
        {% endif %}
    </ul>
    {% endif %}
{% endblock %}

django/apps/games/templates/play_game2.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block page_title %}
Partida {{game.name}}
{% endblock %}

{% block content %}
{% if messages %}
{% endif %}

<div class="container h-100">
    <div class="row align-items-center h-100">
        <div class="col-10 mx-auto">
            <div class="jumbotron" style="padding-top: 0.5rem;">
                <center>
                    <h2>Curso: {{game.course}} - Partida: {{game.name}}</h2>
                </center>
                <div class="row">
                    <div class="col-12">
                        <p>
                            Dentro del mapa de Colombia han ubicado cuatro botones que representan cada una de las culturas precolombinas a estudiar. En la parte inferior se ubican cuatro botones alineados que representan las opciones de respuesta, desde la 1 hasta la 4 de izquierda a derecha.

                        </p>
                        <p>
                            En la parte inferior derecha también hay dos botones de adicionales que permiten reproducir el contenido de nuevo. El botón superior permite reproducir de nuevo la información para responder la pregunta. El botón inferior permite repetir la pregunta y sus opciones de respuesta.
                        </p>
                    </div>
                </div>
                <div class="row" style="display: none;"  id="waiting">
                    <div class="col-12">
                            <strong>Esperando un tema</strong>
                            <img src="https://media1.giphy.com/media/10kTz4r3ishQwU/giphy.gif?cid=790b7611a84b756a32c67c9902eca2409e3e52f57b1cb01a&rid=giphy.gif" height="50" width="50">
                    </div>
                </div>
                <div class="row" style="display: none;" id="topic-data">
                    <div class="col-12">
                        <p id="topic"></p>
                        <hr>
                        <p id="question"></p>
                        <ol id ="options" type="1">
                            <li>
                                <div class="input-group mb-1 alert" id="div-answer_1">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text">
                                            <input type="radio" name="option_selected" />
                                        </span>
                                    </div>
                                    <input type="text" class="form-control" id="answer_1">
                                </div>
                            </li>
                            <li>
                                <div class="input-group mb-1 alert" id="div-answer_2">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text"><input type="radio"
                                                name="option_selected" /></span>
                                    </div>
                                    <input type="text" class="form-control" id="answer_2">
                                </div>
                            </li>
                            <li>
                                <div class="input-group mb-1 alert" id="div-answer_3">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text"><input type="radio"
                                                name="option_selected" /></span>
                                    </div>
                                    <input type="text" class="form-control" id="answer_3">
                                </div>
                            </li>
                            <li>
                                <div class="input-group mb-1 alert" id="div-answer_4">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text"><input type="radio"
                                                name="option_selected" /></span>
                                    </div>
                                    <input type="text" class="form-control" id="answer_4">
                                </div>
                            </li>
                        </ol>
                        <h5 class="text-success" id="correct-answer"></h5>
                    </div>
                </div>
                <div class="row" style="display: none;" id="finished">
                    <div class="col-12">
                        <center>
                            <h1>Gracias por participar!</h1>
                            <h3>nota: <strong id="value-note"></strong></h3>
                        </center>
                    </div>
                </div>
                <div class="row">
                    <button class="btn btn-block btn-warning action" value="on" id="start-game" {% if game.current %}disabled{%endif%}>
                        Iniciar Partida
                    </button>
                    <button class="btn btn-block btn-warning action" value="on" id="stop-game" {% if not game.current %}disabled{%endif%}>
                        Terminar Partida
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block js %}
<script src="https://cdn.socket.io/socket.io-1.4.5.js"></script>
<script type="text/javascript">

//id del juego
var game_id = "{{game.id}}";

//Ajax para iniciar el juego
$("#start-game").click(function(){
	$.ajax({
        url: "{% url 'games:start' %}",
        type: "GET",
        data: {
        	game_id:game_id
        },
        success: function (data) {
        	var response = JSON.parse(data);
            if (response.channel != 'undefined'){
                socket.emit('subscribe', response.channel);
            }
            console.log(response);
        }
    });
});

//Ajax para actualizar el juego
$("#stop-game").click(function(){
	$.ajax({
        url: "{% url 'games:stop' %}",
        type: "GET",
        data: {
        	game_id:game_id
        },
        //
        success: function (data) {
        	var response = JSON.parse(data);
            console.log(response);
        }
    });
});	

/******************************************************************************
********************************* Comunicación ********************************
******************************************************************************/
 // Conectamos con el socket en el servidor de Node
var socket = io('ws://localhost:3000');
var promedio = 0;
var notas = [];

//Recibir mensajes
socket.on('result', function (data) {
    var response = JSON.parse(data);
    console.log(response);
    if (response.type == "start"){
        $("#start-game").prop("disabled", true);
        $("#stop-game").prop("disabled", false);
        $("#waiting").css("display", "inline");
    }else if (response.type == "stop"){
        $("#start-game").prop("disabled", false);
        $("#stop-game").prop("disabled", true);
        resetTopic();
        $("#waiting").css("display", "none");
        $("#finished").css("display", "none");
        $("#value-note").text("");
    }else if (response.type == "topic"){
        showTopic(response.message);
    }else if(response.type == "question"){
        showQuestion(response.message);
    }else if (response.type == "answer"){
        showAnswer(response.answer, response.message);
    }else if (response.type == "confirmation"){
        answerConfirmation(response.answer, response.message);
    }else if(response.type == "reset_question"){
        resetQuestion();
    }else if(response.type == "reset_topic"){
        resetTopic();
    }else if(response.type == "finished"){
        resetTopic();
        finished();
    }else if(response.type == "note"){
        $("#value-note").text(response.value);
    }
});

function showTopic(topic){
    $("#waiting").css("display", "none");
    $("#topic-data").css("display", "inline");
    $("#topic").text(topic);
}

function showQuestion(question){
    $("#question").text(question);
}

function showAnswer(answer_number, answer){
    $("#"+answer_number).val(answer);
}

function answerConfirmation(answer_number, answer){
    if (answer == "") {
        $("#div-"+answer_number).addClass("alert-success");
    } else {
        $("#div-"+answer_number).addClass("alert-danger");
        $("#correct-answer").text("Respuesta correcta: "+answer);
    }
    $("#div-"+answer_number+" input[type='radio']").prop("checked", true);
}

function resetQuestion(){
    $(".alert").removeClass("alert-success");
    $(".alert").removeClass("alert-danger");
    $("input[type='radio']").prop("checked", false);
    $("#correct-answer").text("");
    $("input[type='text']").val("");
    $("#question").text("");
}

function resetTopic(){
    $("#waiting").css("display", "inline");
    $("#topic-data").css("display", "none");
    $("#topic").text(topic);
    resetQuestion();
}

function finished(){
    $("#waiting").css("display", "none");
    $("#finished").css("display", "inline");
}

</script>
{% endblock %}