django/apps/roles/urls.py
from django.urls import path
from .views import *
# from apps.roles.views import RoleListView, RoleCreateView, RoleUpdateView, RoleDeleteView, RoleDetailView

app_name = 'roles'
urlpatterns = [
	path('', RoleListView.as_view(), name='roles'),
	path('create/', RoleCreateView.as_view(), name='create'),
	path('<int:pk>', RoleDetailView.as_view(), name='detail'),
	path('edit/<int:pk>', RoleUpdateView.as_view(), name='edit'),
	path('delete/<int:pk>', RoleDeleteView.as_view(), name='delete')
]

django/diufirstprocjet/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordChangeView, PasswordResetCompleteView
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', TemplateView.as_view(template_name='home.html') , name='home'),
    path('realtime/', include('apps.realtime.urls', namespace='realtime')),
    path('arduino/', include('apps.arduino.urls', namespace='arduino')),
    path('users/', include('apps.users.urls', namespace='users')),
    path('roles/', include('apps.roles.urls', namespace='roles')),
    path('questions/', include('apps.questions.urls', namespace='questions')),
    path('', LoginView.as_view(template_name='login.html'), name="login"),
    path('logout/', LogoutView.as_view(template_name='login.html'), name="logout"),
    path('topics/', include('apps.topics.urls', namespace='topics')),
    path('courses/', include('apps.courses.urls', namespace='courses')),
    path('games/', include('apps.games.urls', namespace='games')),
    path('califications/', include('apps.califications.urls', namespace='califications')),
]

django/apps/roles/models.py
from django.db import models
from django.contrib.auth.models import Group, Permission

class Role(models.Model):
	name = models.CharField(max_length=100, null=False, blank=False)
	permission = models.ManyToManyField(Permission)
	@staticmethod
	def get_roles():
		try:
			queryset = Role.objects.all()
			return queryset
		except Role.DoesNotExist:
			return None
	def __str__(self):
		return self.name

django/apps/roles/forms.py
from django import forms
from django.contrib.auth.models import Group, Permission

class RoleForm(forms.ModelForm):
	permissions = Permission.objects.all()
	class Meta:
		model = Group
		fields = (
			'name',
			'permissions'
		)

django/apps/roles/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import ListView,CreateView,UpdateView,DeleteView,DetailView
from django.contrib.auth.models import Group
from apps.roles.forms import RoleForm
from django.urls import reverse_lazy
from django.contrib.auth.mixins import PermissionRequiredMixin

@method_decorator(login_required, name='dispatch')
class RoleListView(PermissionRequiredMixin, ListView):
    model = Group
    permission_required = 'roles.view_role'
    template_name = 'roles.html'

@method_decorator(login_required, name='dispatch')
class RoleDetailView(PermissionRequiredMixin, DetailView):
    model = Group
    permission_required = 'roles.view_role'
    template_name = 'role_detail.html'

@method_decorator(login_required, name='dispatch')
class RoleCreateView(PermissionRequiredMixin, CreateView):
    model = Group
    permission_required = 'roles.add_role'
    form_class = RoleForm
    template_name = 'role_form.html'
    success_url = reverse_lazy('roles:roles')

@method_decorator(login_required, name='dispatch')
class RoleUpdateView(PermissionRequiredMixin, UpdateView):
    model = Group
    permission_required = 'roles.change_role'
    form_class = RoleForm
    template_name = 'role_form.html'
    success_url = reverse_lazy('roles:roles')

@method_decorator(login_required, name='dispatch')
class RoleDeleteView(PermissionRequiredMixin, DeleteView):
    model = Group
    permission_required = 'roles.delete_role'
    success_url = reverse_lazy('roles:roles')

django/apps/roles/templates/role_detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block page_title %}
    Crear Role
{% endblock %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-lg-6 col-md-6 col-sm-12">
			<div class="form-group">
				<label>Nombre</label>
				<input type="text" value="{{role.name}}" class="form-control">
			</div>
		</div>
	</div>
</div>
{% endblock %}

django/apps/roles/templates/role_form.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block page_title %}
    Crear Usuario
{% endblock %}

{% block content %}
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-warning">
    </form>
{% endblock %}

django/apps/roles/templates/roles.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block page_title %}
    Listado de roles
{% endblock %}

{% block content %}
    <a class="btn btn-info float-right" href="{% url 'roles:create' %}">Nuevo Rol</a>
    <br>
    <hr>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Nombre</th>
                <th class="text-center">Opciones</th>
            </tr>
        </thead>
        <tbody>
            {% for role in object_list %}
            <tr>
                <td>{{ role.name }}</td>
                <td class="text-center">
                    <a class="btn text-danger" href="{% url 'roles:edit' pk=role.id %}"><i class="fas fa-edit"></i></a>
                    <a class="btn text-info" href="{% url 'roles:detail' pk=role.id %}"><i class="far fa-eye"></i></a>
                    <button class="btn text-danger" data-toggle="modal" data-target="#delete_modal_{{ role.id }}">
                        <i class="far fa-trash-alt"></i>
                    </button>
                    <div class="modal fade" id="delete_modal_{{ role.id }}" tabindex="-1">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">Eliminar</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    Esta seguro de elimiar el rol "{{ role.name }}"?
                                </div>
                                <div class="modal-footer">
                                    <form action="{% url 'roles:delete' role.id %}" method="POST">
                                        {% csrf_token %}
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                                        <button type="submit" class="btn btn-danger">Aceptar</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    {% if roles.has_other_pages %}
    <ul class="pagination">
        {% if roles.has_previous %}
        <li><a href="?page={{ roles.previous_page_number }}">&laquo;</a></li>
        {% else %}
        <li class="disabled"><span>&laquo;</span></li>
        {% endif %}
        {% for i in roles.paginator.page_range %}
        {% if roles.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
        {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
        {% endif %}
        {% endfor %}
        {% if roles.has_next %}
        <li><a href="?page={{ roles.next_page_number }}">&raquo;</a></li>
        {% else %}
        <li class="disabled"><span>&raquo;</span></li>
        {% endif %}
    </ul>
    {% endif %}
{% endblock %}